# Generated by Django 2.2 on 2020-09-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_auto_20200909_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
